broker:
  type: rabbitmq
  username: "username"
  password: "password"
  port: 5672

bots:
  fish:
    image: "fishbowl_fish"
    mount: [ ]
    lifecycle:
      type: proactive
      initialDelay: 5
      period: 5
    publish:
      key: "fish_movement"
      order: "move_fish"
    subscribe: [ ]
    instances:
      fish_1:
        persistent: true
        environment:
          - FISH_SILHOUETTE=1
          - FISH_POSITION_X=0
          - FISH_POSITION_Y=0
      fish_2:
        persistent: true
        lifecycle:
          type: proactive
          initialDelay: 5
          period: 10
        environment:
          - FISH_SILHOUETTE=2
          - FISH_POSITION_X=5
          - FISH_POSITION_Y=5
  manager:
    image: "fishbowl_manager"
    mount:
      - source: "./fishbowl"
        target: "/app/fishbowl"
    lifecycle:
      type: reactive
      order: "move_fish"
    publish:
      key: "test"
      order: "test"
    subscribe: [ "fish_movement" ]
    instances:
      manager_1:
        persistent: true
        environment: [ ]
